### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar una pelicula por id
GET http://localhost:1234/movies/c2095a96-2411-11f0-a11e-cc28aa1196bd

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=drama

### Crear una película con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime",
        "Drama"
    ]
}

### Eliminar una película
DELETE http://localhost:1234/movies/de1c1775-2417-11f0-a11e-cc28aa1196bd

### Actualizar una película
PATCH http://localhost:1234/movies/084e2cd1-2418-11f0-a11e-cc28aa1196bd
Content-Type: application/json

{
    "year": 1993
}